version: '3'

services:

  comptages-db:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=comptages
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: "no"
    ports:
      - 5432:5432
    networks:
      - net
    
  qgis:
    image: qgis/qgis:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../.:/tests_directory \
    environment:
      - DISPLAY=:99 \
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
